/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    GameRow: typeof import('./components/GameRow.vue')['default']
    HelloComponent: typeof import('./components/HelloComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAutocomplete: typeof import('./components/SearchAutocomplete.vue')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
}
