/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    GameRow: typeof import('./components/GameRow.vue')['default']
    HelloComponent: typeof import('./components/HelloComponent.vue')['default']
    JsonViewer: typeof import('./components/JsonViewer.vue')['default']
    LoadingDialog: typeof import('./components/LoadingDialog.vue')['default']
    PlayerGameLog: typeof import('./components/PlayerGameLog.vue')['default']
    PlayerQuickList: typeof import('./components/PlayerQuickList.vue')['default']
    PlayerSplits: typeof import('./components/PlayerSplits.vue')['default']
    PlayerStats: typeof import('./components/PlayerStats.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAutocomplete: typeof import('./components/SearchAutocomplete.vue')['default']
    TeamHeader: typeof import('./components/team/TeamHeader.vue')['default']
    TeamLeaders: typeof import('./components/team/TeamLeaders.vue')['default']
    TeamRoster: typeof import('./components/team/TeamRoster.vue')['default']
    TeamSchedule: typeof import('./components/team/TeamSchedule.vue')['default']
  }
}
