# Generated by Django 5.2.5 on 2025-08-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerIdInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_person", models.CharField(max_length=20, null=True)),
                ("key_uuid", models.CharField(max_length=40, null=True)),
                ("key_mlbam", models.CharField(max_length=20, null=True)),
                ("key_retro", models.CharField(max_length=20, null=True)),
                ("key_bbref", models.CharField(max_length=20, null=True)),
                ("key_bbref_minors", models.CharField(max_length=20, null=True)),
                ("key_fangraphs", models.CharField(max_length=20, null=True)),
                ("key_npb", models.CharField(max_length=20, null=True)),
                ("name_last", models.CharField(max_length=100, null=True)),
                ("name_first", models.CharField(max_length=100, null=True)),
                ("name_given", models.CharField(max_length=100, null=True)),
                ("name_suffix", models.CharField(max_length=10, null=True)),
                (
                    "name_full",
                    models.GeneratedField(
                        expression=models.functions.Concat(
                            models.F("name_first"),
                            models.Value(" "),
                            models.F("name_last"),
                        ),
                        output_field=models.CharField(max_length=200),
                        db_persist=True,
                    ),
                ),
            ],
            options={
                "db_table": "player_id_infos",
            },
        ),
    ]
    Migration.operations += [
        migrations.AddIndex(
            model_name="playeridinfo",
            index=models.Index(fields=["name_full"], name="pidinfo_full_idx"),
        ),
        migrations.AddIndex(
            model_name="playeridinfo",
            index=models.Index(fields=["name_last"], name="pidinfo_last_idx"),
        ),
    ]
