# Generated by Django 5.2.5 on 2025-08-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerIdInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("external_id", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "player_id_infos",
            },
        ),
    ]
