# Generated by Django 5.2.5 on 2025-08-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_teamidinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mlbam_id", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("link", models.CharField(max_length=255, null=True)),
                ("active", models.BooleanField(null=True)),
                ("season", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "venues",
            },
        ),
    ]

