# Generated by Django 5.2.5 on 2025-09-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_venue"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallOfFameVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bbref_id", models.CharField(max_length=20, null=True)),
                ("year", models.IntegerField(null=True)),
                ("voted_by", models.CharField(max_length=100, null=True)),
                ("ballots", models.IntegerField(null=True)),
                ("needed", models.IntegerField(null=True)),
                ("votes", models.IntegerField(null=True)),
                ("inducted", models.BooleanField(null=True)),
                ("category", models.CharField(max_length=50, null=True)),
                ("needed_note", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "hall_of_fame_votes",
            },
        ),
    ]
